### ISSUE TITLE
Address Book WebExtensions API custom properties

### ISSUE THREAD

**Issue by courteous** [thundernest/sample-extensions#17]
Hello and thank you for this repo, it really helps to understand the things better. I have a question here related to how new contacts are created. I am in the middle of creating an address book synchronization add-on for TB and thus the question. 

The TB WebExtensions API states that the complete list of properties that TB uses should be taken from the nsIAbCard.idl i.e.

https://thunderbird-webextensions.readthedocs.io/en/latest/contacts.html#contactproperties

the nsIAbCard.idl interface provided the opportunity to create a custom property using the methods

```
void setProperty(in AUTF8String name, in nsIVariant value);
nsIVariant getProperty(in AUTF8String name, in nsIVariant defaultValue);
```
Is it possible to create those properties using the new address book API for the AddressBook node?

The reason i am asking this question is because i found myself in the need to tag each Node (Address Book, Contact, MailingList) with at least the first two of the 3 properties mentioned below:

1. Integer Counter - which increases every time the contact is changed.
2. Epoch time stamp  integer - that is set to the current time stamp every time the contact has been changed. 
3. UUID - that will be set from external source in order to identify this contact . Here i do not mean the ID that is created by the 

contact WebExtensions API i.e. i mean UUID string that is received from another program. 

I could create a contact like that : 

```
function createContact() {
  	let randomId = Math.random(); 
	let currentTimeStamp = new Date().getTime().toString(); 
	let counter = Math.random().toString();
	let uuid = "b0fe4bd6-eb2b-41a7-b49e-4fe37fd22813";
	
	let properties = { PreferMailFormat: "0", DisplayName: "TestContact33" + randomId , MyCustomerCounteProperty:counter, LastModifiedDate:currentTimeStamp, MyCustomeUUIDProperty:uuid  };
	let addressBookId="9c0e538f-a29f-4060-b5d8-21a3e788e5c6";
	let promise = browser.contacts.create(parentId = addressBookId, properties).then(() => {  });
}
```
Here i am adding the custome properties "MyCustomerCounteProperty", and "MyCustomeUUIDProperty"
 I am searching for more clean approach to do the same for the AddressBook Node type and Mailing List.

The documentation mentioned that for Contacts
"It is also possible to store custom properties. The custom property name however may only use a to z, A to Z, 1 to 9 and underscores."

however i am not able to execute some customer property for the AddressBook node, i can execute that for Contacts only! Can customer property be executed on AddressBook nodes and Mailing lists?

**Comment by jobisoft** [comment]
Wow, I did not get notified on this issue. I will check the API and get back to you soon.

**Comment by jobisoft** [comment]
The contact handling has changed dramatically in Thunderbird 102. We still have the "property bag", but most properties have been removed and are now stored inside a vCard string in the _vCard property. The same is valid for the webExtension API, but here the property is just called "vCard".

https://webextension-api.thunderbird.net/en/102/how-to/contacts.html

You can still use custom properties in the property bag (best is to prefix them with an `X-`), in legacy as well as in the WebExtension API.

I suggest to no longer use Experiments to access contacts, but only use the WebExtension API.

If your add-on is actually creating a provider for address books, please ping me directly, because I am in the process of creating an API and having real world use cases helps to shape the API.

john at thunderbird.net

More details can be found here:
